internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/savesjkf/save-71-admin/app.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/savesjkf/save-71-admin/app.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/savesjkf/save-71-admin/app.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/savesjkf/save-71-admin/app.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/savesjkf/save-71-admin/app.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/savesjkf/save-71-admin/app.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /home/savesjkf/save-71-admin/app.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/savesjkf/save-71-admin/app.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/savesjkf/save-71-admin/app.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 1 Expected: 50
    at Parser._tryReadPacketHeader (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:400:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 1 Expected: 50
    at Parser._tryReadPacketHeader (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:400:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
Error occurred while adding sub category: null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 1 Expected: 114
    at Parser._tryReadPacketHeader (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:400:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}
Error occurred while adding sub category: null
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:371:10)
    at Connection._handleNetworkError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:371:10)
    at Connection._handleNetworkError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:400:28)
    at Protocol._delegateError (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/savesjkf/nodevenv/save-71-admin/14/lib/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
